"use strict";

const DATA_ROLES = Object.freeze({
  TRANSPORT_RAW: 'TRANSPORT_RAW',
  IDENTITY_MASTER: 'IDENTITY_MASTER',
  SEMANTIC_MASTER: 'SEMANTIC_MASTER',
  ASSERTION: 'ASSERTION',
  EVIDENCE_RECORD: 'EVIDENCE_RECORD',
  CURRENT_STATE: 'CURRENT_STATE',
  HISTORICAL_RECORD: 'HISTORICAL_RECORD',
  TARGET_STATE: 'TARGET_STATE',
  PREDICTED_STATE: 'PREDICTED_STATE',
  RELATION_MASTER: 'RELATION_MASTER',
  EXECUTION_CONTROL: 'EXECUTION_CONTROL',
  RESULT_RECORD: 'RESULT_RECORD',
  AUDIT_PROVENANCE: 'AUDIT_PROVENANCE',
  CONFLICT_RECORD: 'CONFLICT_RECORD',
  ROUTING_INDEX: 'ROUTING_INDEX',
  SEARCH_PROJECTION: 'SEARCH_PROJECTION',
  CACHE: 'CACHE'
});

const DATA_ROLE_LIST = Object.freeze(Object.values(DATA_ROLES));

module.exports = { DATA_ROLES, DATA_ROLE_LIST };
