'use strict';

/**
 * Ci Graph — canonical versioned registry of all axes and enums.
 * Version: cigraf-1.0
 *
 * Hard invariant: this file is append-only for new values.
 * Existing values must never be renamed or removed; add DEPRECATED_ prefix instead.
 */

const CLASSIFIER_VERSION = 'cigraf-1.0';

// ── A. Ci+ scope ──────────────────────────────────────────────────────────────
const SCOPE = Object.freeze({
  CORE: 'CORE',
  HOME: 'HOME',
  LIFE: 'LIFE',
  WORK: 'WORK',
  FIN: 'FIN',
  DATA: 'DATA',
  ACTION: 'ACTION',
});

// ── B. Functional domain registry ────────────────────────────────────────────
const DOMAIN = Object.freeze({
  // Core
  IDENTITY_ACCESS: 'IDENTITY_ACCESS',
  GRAPH_SEMANTICS: 'GRAPH_SEMANTICS',
  ORCHESTRATION: 'ORCHESTRATION',
  POLICY_GOVERNANCE: 'POLICY_GOVERNANCE',
  OBSERVABILITY: 'OBSERVABILITY',
  VERIFICATION: 'VERIFICATION',
  SECURITY_PRIVACY: 'SECURITY_PRIVACY',
  // Home
  HOUSING_SPACE: 'HOUSING_SPACE',
  ASSET_REGISTRY: 'ASSET_REGISTRY',
  ENERGY: 'ENERGY',
  WATER: 'WATER',
  CLIMATE: 'CLIMATE',
  NETWORK_COMPUTE: 'NETWORK_COMPUTE',
  SAFETY_SECURITY: 'SAFETY_SECURITY',
  MAINTENANCE: 'MAINTENANCE',
  STORAGE_BACKUP: 'STORAGE_BACKUP',
  DOCUMENTS_COMPLIANCE: 'DOCUMENTS_COMPLIANCE',
  // Life
  PEOPLE_RELATIONS: 'PEOPLE_RELATIONS',
  FAMILY: 'FAMILY',
  ROUTINES: 'ROUTINES',
  LEARNING: 'LEARNING',
  CREATIVITY: 'CREATIVITY',
  TRAVEL: 'TRAVEL',
  FOOD: 'FOOD',
  WELLBEING: 'WELLBEING',
  COMMUNICATION: 'COMMUNICATION',
  // Work
  PROJECTS: 'PROJECTS',
  SOURCE_CONTROL: 'SOURCE_CONTROL',
  SOFTWARE_SYSTEMS: 'SOFTWARE_SYSTEMS',
  DEPLOYMENT: 'DEPLOYMENT',
  OPERATIONS: 'OPERATIONS',
  COLLABORATION: 'COLLABORATION',
  PRODUCT: 'PRODUCT',
  RESEARCH: 'RESEARCH',
  // Finance
  ACCOUNTS: 'ACCOUNTS',
  PAYMENTS: 'PAYMENTS',
  BUDGET: 'BUDGET',
  PURCHASES: 'PURCHASES',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  OBLIGATIONS: 'OBLIGATIONS',
  VALUATION: 'VALUATION',
  // Data
  FILES: 'FILES',
  DOCUMENTS: 'DOCUMENTS',
  MEDIA: 'MEDIA',
  MEMORY: 'MEMORY',
  KNOWLEDGE: 'KNOWLEDGE',
  DATASETS: 'DATASETS',
  ARCHIVE: 'ARCHIVE',
  PROVENANCE: 'PROVENANCE',
  // Action
  SIGNALS: 'SIGNALS',
  EVENTS: 'EVENTS',
  TASKS: 'TASKS',
  AUTOMATION: 'AUTOMATION',
  SCHEDULING: 'SCHEDULING',
  NOTIFICATIONS: 'NOTIFICATIONS',
  EXECUTION: 'EXECUTION',
  RESULTS: 'RESULTS',
});

/** Map scope → set of valid domains for that scope */
const SCOPE_DOMAINS = Object.freeze({
  [SCOPE.CORE]: new Set([
    DOMAIN.IDENTITY_ACCESS, DOMAIN.GRAPH_SEMANTICS, DOMAIN.ORCHESTRATION,
    DOMAIN.POLICY_GOVERNANCE, DOMAIN.OBSERVABILITY, DOMAIN.VERIFICATION,
    DOMAIN.SECURITY_PRIVACY,
  ]),
  [SCOPE.HOME]: new Set([
    DOMAIN.HOUSING_SPACE, DOMAIN.ASSET_REGISTRY, DOMAIN.ENERGY, DOMAIN.WATER,
    DOMAIN.CLIMATE, DOMAIN.NETWORK_COMPUTE, DOMAIN.SAFETY_SECURITY,
    DOMAIN.MAINTENANCE, DOMAIN.STORAGE_BACKUP, DOMAIN.DOCUMENTS_COMPLIANCE,
  ]),
  [SCOPE.LIFE]: new Set([
    DOMAIN.PEOPLE_RELATIONS, DOMAIN.FAMILY, DOMAIN.ROUTINES, DOMAIN.LEARNING,
    DOMAIN.CREATIVITY, DOMAIN.TRAVEL, DOMAIN.FOOD, DOMAIN.WELLBEING,
    DOMAIN.COMMUNICATION,
  ]),
  [SCOPE.WORK]: new Set([
    DOMAIN.PROJECTS, DOMAIN.SOURCE_CONTROL, DOMAIN.SOFTWARE_SYSTEMS,
    DOMAIN.DEPLOYMENT, DOMAIN.OPERATIONS, DOMAIN.COLLABORATION,
    DOMAIN.PRODUCT, DOMAIN.RESEARCH,
  ]),
  [SCOPE.FIN]: new Set([
    DOMAIN.ACCOUNTS, DOMAIN.PAYMENTS, DOMAIN.BUDGET, DOMAIN.PURCHASES,
    DOMAIN.SUBSCRIPTIONS, DOMAIN.OBLIGATIONS, DOMAIN.VALUATION,
  ]),
  [SCOPE.DATA]: new Set([
    DOMAIN.FILES, DOMAIN.DOCUMENTS, DOMAIN.MEDIA, DOMAIN.MEMORY,
    DOMAIN.KNOWLEDGE, DOMAIN.DATASETS, DOMAIN.ARCHIVE, DOMAIN.PROVENANCE,
  ]),
  [SCOPE.ACTION]: new Set([
    DOMAIN.SIGNALS, DOMAIN.EVENTS, DOMAIN.TASKS, DOMAIN.AUTOMATION,
    DOMAIN.SCHEDULING, DOMAIN.NOTIFICATIONS, DOMAIN.EXECUTION, DOMAIN.RESULTS,
  ]),
});

// ── C. Primary structural class ───────────────────────────────────────────────
const CLASS = Object.freeze({
  // World/identity
  ACTOR: 'ACTOR',
  ENVIRONMENT: 'ENVIRONMENT',
  SPACE: 'SPACE',
  ORGANIZATION: 'ORGANIZATION',
  // Things/resources
  ASSET: 'ASSET',
  DEVICE: 'DEVICE',
  COMPONENT: 'COMPONENT',
  RESOURCE: 'RESOURCE',
  MATERIAL: 'MATERIAL',
  // Digital
  SYSTEM: 'SYSTEM',
  SERVICE: 'SERVICE',
  APPLICATION: 'APPLICATION',
  REPOSITORY: 'REPOSITORY',
  ACCOUNT: 'ACCOUNT',
  CHANNEL: 'CHANNEL',
  INTERFACE: 'INTERFACE',
  CREDENTIAL_REF: 'CREDENTIAL_REF',
  // Information
  DOCUMENT: 'DOCUMENT',
  FILE: 'FILE',
  MEDIA_ITEM: 'MEDIA_ITEM',
  DATASET: 'DATASET',
  RECORD: 'RECORD',
  KNOWLEDGE_ITEM: 'KNOWLEDGE_ITEM',
  MEMORY_ITEM: 'MEMORY_ITEM',
  // Dynamics
  SIGNAL: 'SIGNAL',
  CLAIM: 'CLAIM',
  STATE: 'STATE',
  EVENT: 'EVENT',
  INTENT: 'INTENT',
  DECISION: 'DECISION',
  TASK: 'TASK',
  ACTION: 'ACTION',
  PROCESS: 'PROCESS',
  SCENARIO: 'SCENARIO',
  AUTOMATION: 'AUTOMATION',
  RESULT: 'RESULT',
  // Governance/assurance
  POLICY: 'POLICY',
  RULE: 'RULE',
  PERMISSION: 'PERMISSION',
  RISK: 'RISK',
  ALERT: 'ALERT',
  EVIDENCE: 'EVIDENCE',
  METRIC: 'METRIC',
  CHECK: 'CHECK',
  GAP: 'GAP',
  CONFLICT: 'CONFLICT',
  UNKNOWN_CLASS: 'UNKNOWN_CLASS',
});

// ── D. Temporal layer ─────────────────────────────────────────────────────────
const TEMPORAL_LAYER = Object.freeze({
  HIST: 'HIST',
  ACTUAL: 'ACTUAL',
  TARGET: 'TARGET',
  PREDICTED: 'PREDICTED',
  UNKNOWN_TIME: 'UNKNOWN_TIME',
});

// ── E. Epistemic/truth status ─────────────────────────────────────────────────
const TRUTH_STATUS = Object.freeze({
  RAW: 'RAW',
  PARSED: 'PARSED',
  CLAIMED: 'CLAIMED',
  CANDIDATE: 'CANDIDATE',
  OBSERVED: 'OBSERVED',
  VERIFIED: 'VERIFIED',
  CONFLICTING: 'CONFLICTING',
  REJECTED: 'REJECTED',
  UNKNOWN: 'UNKNOWN',
});

// ── F. Provenance source types ────────────────────────────────────────────────
const SOURCE_TYPE = Object.freeze({
  USER: 'user',
  DEVICE: 'device',
  SENSOR: 'sensor',
  SERVICE: 'service',
  REPO: 'repo',
  DOCUMENT: 'document',
  FILE: 'file',
  CONNECTOR: 'connector',
  AUTOMATION: 'automation',
  AI: 'ai',
  DERIVED: 'derived',
});

// ── G. Relation types ─────────────────────────────────────────────────────────
const RELATION = Object.freeze({
  // Structural
  CONTAINS: 'CONTAINS',
  PART_OF: 'PART_OF',
  MEMBER_OF: 'MEMBER_OF',
  LOCATED_IN: 'LOCATED_IN',
  CONNECTED_TO: 'CONNECTED_TO',
  MOUNTED_ON: 'MOUNTED_ON',
  ASSIGNED_TO: 'ASSIGNED_TO',
  OWNED_BY: 'OWNED_BY',
  MANAGED_BY: 'MANAGED_BY',
  // Operational
  DEPENDS_ON: 'DEPENDS_ON',
  REQUIRES: 'REQUIRES',
  PROVIDES: 'PROVIDES',
  POWERS: 'POWERS',
  SUPPLIES: 'SUPPLIES',
  CONTROLS: 'CONTROLS',
  MONITORS: 'MONITORS',
  ROUTES_TO: 'ROUTES_TO',
  STORES_IN: 'STORES_IN',
  BACKS_UP_TO: 'BACKS_UP_TO',
  SYNCS_WITH: 'SYNCS_WITH',
  AUTHENTICATES_VIA: 'AUTHENTICATES_VIA',
  EXECUTES_ON: 'EXECUTES_ON',
  EXPOSES: 'EXPOSES',
  USES: 'USES',
  // Semantic/causal
  DESCRIBES: 'DESCRIBES',
  EVIDENCES: 'EVIDENCES',
  ASSERTS: 'ASSERTS',
  DERIVED_FROM: 'DERIVED_FROM',
  SUPERSEDES: 'SUPERSEDES',
  CONTRADICTS: 'CONTRADICTS',
  CORRELATES_WITH: 'CORRELATES_WITH',
  CAUSES: 'CAUSES',
  TRIGGERS: 'TRIGGERS',
  AFFECTS: 'AFFECTS',
  RESOLVES: 'RESOLVES',
  // Action lifecycle
  REQUESTS: 'REQUESTS',
  TARGETS: 'TARGETS',
  AUTHORIZED_BY: 'AUTHORIZED_BY',
  EXECUTED_BY: 'EXECUTED_BY',
  PRODUCES: 'PRODUCES',
  VERIFIED_BY: 'VERIFIED_BY',
  BLOCKED_BY: 'BLOCKED_BY',
  ROLLS_BACK: 'ROLLS_BACK',
});

/** Relations that require explicit causal evidence — must never be inferred from co-occurrence */
const CAUSAL_RELATIONS = Object.freeze(new Set([RELATION.CAUSES]));

// ── H. Canonical lifecycle state ──────────────────────────────────────────────
const LIFECYCLE_STATE = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  DISCOVERED: 'DISCOVERED',
  REGISTERED: 'REGISTERED',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
  DEGRADED: 'DEGRADED',
  FAILED: 'FAILED',
  BLOCKED: 'BLOCKED',
  PENDING: 'PENDING',
  PLANNED: 'PLANNED',
  RUNNING: 'RUNNING',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED',
  RETIRED: 'RETIRED',
});

// ── I. Execution class ────────────────────────────────────────────────────────
const EXECUTION_CLASS = Object.freeze({
  OBSERVE: 'OBSERVE',
  RECOMMEND: 'RECOMMEND',
  PREPARE: 'PREPARE',
  EXECUTE_REVERSIBLE: 'EXECUTE_REVERSIBLE',
  EXECUTE_EXTERNAL: 'EXECUTE_EXTERNAL',
  EXECUTE_PHYSICAL: 'EXECUTE_PHYSICAL',
  EXECUTE_FINANCIAL: 'EXECUTE_FINANCIAL',
  EXECUTE_SAFETY_CRITICAL: 'EXECUTE_SAFETY_CRITICAL',
});

// ── J. Risk/criticality ───────────────────────────────────────────────────────
const CRITICALITY = Object.freeze({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

// ── Kind ──────────────────────────────────────────────────────────────────────
const KIND = Object.freeze({
  NODE: 'NODE',
  EDGE: 'EDGE',
  STATE: 'STATE',
  EVENT: 'EVENT',
  ACTION: 'ACTION',
  EVIDENCE: 'EVIDENCE',
});

module.exports = {
  CLASSIFIER_VERSION,
  SCOPE,
  DOMAIN,
  SCOPE_DOMAINS,
  CLASS,
  TEMPORAL_LAYER,
  TRUTH_STATUS,
  SOURCE_TYPE,
  RELATION,
  CAUSAL_RELATIONS,
  LIFECYCLE_STATE,
  EXECUTION_CLASS,
  CRITICALITY,
  KIND,
};
