const TASK_STATUS = {
  CREATED: 'CREATED',
  CLASSIFIED: 'CLASSIFIED',
  ROUTED: 'ROUTED',
  WAITING_PERMISSION: 'WAITING_PERMISSION',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',
  BLOCKED: 'BLOCKED',
  FAILED: 'FAILED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  UNKNOWN: 'UNKNOWN'
};

const COMPLETION_POLICIES = {
  ALL_VERIFIERS: 'all_verifiers',
  ANY_VERIFIER: 'any_verifier'
};

const AGGREGATION_POLICIES = {
  ALL_REQUIRED: 'all_required',
  ANY_SUCCESS: 'any_success',
  QUORUM: 'quorum',
  BEST_EFFORT: 'best_effort'
};

const APPROVAL_POLICIES = {
  AUTO: 'auto',
  REQUIRE_HUMAN: 'require_human'
};

const VERIFIER_STATUS = {
  PASS: 'pass',
  FAIL: 'fail',
  PENDING: 'pending'
};

const CLASSIFICATIONS = {
  FACT: 'fact',
  INTENT: 'intent',
  TASK: 'task',
  EVENT: 'event',
  MEMORY: 'memory',
  SERVICE_ACTION: 'service_action',
  DEVICE_ACTION: 'device_action',
  REPO_ACTION: 'repo_action',
  DEPLOY_ACTION: 'deploy_action',
  HUMAN_ACTION: 'human_action',
  UNKNOWN: 'unknown'
};

const EXECUTION_CENTERS = {
  LOCAL: 'local',
  MEMORY: 'memory',
  AI: 'ai',
  SERVICE: 'service',
  REPO: 'repo',
  DEVICE: 'device',
  HUMAN: 'human'
};

const PERMISSION_LEVELS = {
  L0_READ: 'L0_READ',
  L1_DRAFT: 'L1_DRAFT',
  L2_LOCAL_WRITE: 'L2_LOCAL_WRITE',
  L3_REPO_WRITE: 'L3_REPO_WRITE',
  L4_EXTERNAL_API_WRITE: 'L4_EXTERNAL_API_WRITE',
  L5_DEPLOY_OR_DEVICE_ACTION: 'L5_DEPLOY_OR_DEVICE_ACTION'
};

module.exports = {
  TASK_STATUS,
  CLASSIFICATIONS,
  EXECUTION_CENTERS,
  PERMISSION_LEVELS,
  COMPLETION_POLICIES,
  AGGREGATION_POLICIES,
  APPROVAL_POLICIES,
  VERIFIER_STATUS
};
